# Generated by Django 3.2.5 on 2022-09-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220910_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suburb',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
